spring:
  application:
    name: sb-ecommerce
  datasource:
    url: jdbc:mysql://localhost:3306/ecom_db
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"